name: Coffee Roulette Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_coffee_roulette:
        description: 'Run Coffee Roulette'
        required: false
        default: 'false'
        type: boolean

env:
  ARTIFACT_NAME: "latest_coffee_roulette.csv"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          mkdir -p artifacts
          
      - name: Handle artifacts
        run: bash ci_scripts/handle_artifacts.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Copy people file
        run: cp src/people.txt artifacts/
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: setup-artifacts
          path: artifacts/

  npm_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/

  test:
    runs-on: ubuntu-latest
    needs: npm_install
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
      - name: Run tests
        run: npm test

  e2e_test:
    runs-on: ubuntu-latest
    needs: npm_install
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/
          
      - name: Run E2E tests
        run: bash tests/e2e/test_coffee_roulette.sh
        
      - name: Upload E2E artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-artifacts
          path: e2e_test_artifacts/
          retention-days: 1

  coffee_roulette_run_script:
    runs-on: ubuntu-latest
    needs: [setup, npm_install]
    if: github.event.inputs.run_coffee_roulette == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-artifacts
          path: artifacts/
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/
          
      - name: Run coffee roulette
        run: bash ci_scripts/run_coffee_roulette.sh
        
      - name: Upload run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coffee-roulette-results
          path: |
            src/assigned_pairs_run_*.csv
            artifacts/${{ env.ARTIFACT_NAME }}
            artifacts/people.txt
            artifacts/latest_csv.env

  display_csv:
    runs-on: ubuntu-latest
    needs: coffee_roulette_run_script
    if: github.event.inputs.run_coffee_roulette == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download coffee roulette results
        uses: actions/download-artifact@v4
        with:
          name: coffee-roulette-results
          path: ./
          
      - name: Display CSV content
        run: |
          echo "Displaying content of ${{ env.ARTIFACT_NAME }}"
          cat artifacts/${{ env.ARTIFACT_NAME }}

  send_slack_notification:
    runs-on: ubuntu-latest
    needs: coffee_roulette_run_script
    if: github.event.inputs.run_coffee_roulette == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download coffee roulette results
        uses: actions/download-artifact@v4
        with:
          name: coffee-roulette-results
          path: ./
          
      - name: Send Slack notification
        run: sh ci_scripts/send_slack_notification.sh
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}
